CREATE DATABASE IF NOT EXISTS devicesdb;
USE devicesdb;

CREATE TABLE devices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  mac VARCHAR(32) NOT NULL UNIQUE,
  status ENUM('ATIVO','INATIVO') NOT NULL DEFAULT 'ATIVO',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

